### ISSUE TITLE
[FEAT] 운동 리스트 조회 및 운동 리스트 순서 변경 API 구현

### ISSUE THREAD

**Issue by chaewonni** [NOW-SOPT-APP3-PlanFit/PlanFit-SERVER#9]
## 🛠 Issue

운동 리스트 조회 및 운동 리스트 순서 변경 API 구현

## 📝 To-do

- [x] 운동 리포지토리, 서비스 추가
- [x] 운동 리스트뷰 GET API 구현
- [ ] 운동 리스트뷰 순서 변경 PUT API 구현
